version: "3.3"
networks:
  web:
    external: true
services:
  admin-panel:
    build: .
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin-panel.rule=Host(`console.rigami.io`)"
      - "traefik.http.routers.admin-panel.entrypoints=web-http,web-https"
      - "traefik.http.routers.admin-panel.tls=true"
      - "traefik.http.routers.admin-panel.tls.certresolver=letsEncrypt"
      - "traefik.http.services.admin-panel-service.loadbalancer.server.port=80"
