version: "3.3"
networks:
  web:
    external: true
services:
  rigami-console:
    build: .
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rigami-console.rule=Host(`console.rigami.io`)"
      - "traefik.http.routers.rigami-console.entrypoints=web-http,web-https"
      - "traefik.http.routers.rigami-console.tls=true"
      - "traefik.http.routers.rigami-console.tls.certresolver=letsEncrypt"
      - "traefik.http.services.rigami-console-service.loadbalancer.server.port=80"
